services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Volume for certbot challenge files
      - ./data/certbot/www:/var/www/certbot:ro
      # Volumes for certificates
      - ./data/certbot/conf:/etc/letsencrypt
    depends_on:
      - app-service
      - auth-service
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/www:/var/www/certbot:rw
      - ./data/certbot/conf:/etc/letsencrypt
    # Replace 'command:' with 'entrypoint:'
    entrypoint: sh -c "while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;"
    networks:
      - app-network

  app-service:
    image: gabrielhsc95/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-auth-service}
    depends_on:
      auth-service:
        condition: service_started
    networks:
      - app-network

  auth-service:
    image: gabrielhsc95/auth-service
    restart: "always"
    networks:
      - app-network
    environment:
      JWT_SECRET: ${JWT_SECRET} 

# Remove old volumes, we are using bind mounts now for clarity
# volumes:
#  certbot-etc:
#  certbot-var:
  
networks:
  app-network:
    driver: bridge